### ISSUE TITLE
加载有问题昂

### ISSUE THREAD

**Issue by Jason9520** [zcmimi/music-playlist-downloader#1]
歌单id加载完，不显示名字和图片，
![WHCHIG@V`B63J0I 7 PYO4C](https://user-images.githubusercontent.com/32565106/81250828-7f8fbb00-9054-11ea-823e-e3693a6aecf8.png)

**Comment by zcmimi** [comment]
> 歌单id加载完，不显示名字和图片，
> ![WHCHIG@V`B63J0I 7 PYO4C](https://user-images.githubusercontent.com/32565106/81250828-7f8fbb00-9054-11ea-823e-e3693a6aecf8.png)

修好了

**Comment by zcmimi** [comment]
@Jason9520 修好了

**Comment by Jason9520** [comment]
> @ Jason9520修好了

好的，辛苦了。还有个疑问就是这个可能会卡死是客户端还是服务器端？我想应该是客户端吧。
![O_GKIS)SLVIR3E1~(5 0X)E](https://user-images.githubusercontent.com/32565106/81298133-ed64d280-90a6-11ea-8129-b7f124007c7c.png)

**Comment by zcmimi** [comment]
@Jason9520 客户端,这个是静态网页.不知道某些运行内存较小的电脑不知道会不会卡死,这个是通过xmlhttprequest下载文件的

**Comment by Jason9520** [comment]
> @ Jason9520客户端，这个是静态网页。不知道某些正在运行内存较小的电脑不知道会不会卡死，这个是通过xmlhttprequest下载文件的

清楚了，谢谢哈
